/* chinese-data.js - Dữ liệu 301 thẻ từ vựng YCT 1-4 cho mục "Tiếng Trung YCT".
 *
 * Nguồn: bộ flashcard YCT1-YCT4 (Lingo Bus) dạng PDF ảnh. Chữ Hán, pinyin,
 * nghĩa tiếng Anh và câu ví dụ chép lại từ mặt sau thẻ; nghĩa tiếng Việt
 * dịch thêm. Hình minh hoạ cắt từ mặt trước, lưu ở img/<id>.webp.
 *
 * Trường:
 *   id     "<cấp>-<tờ>-<vị trí>" (trùng tên file ảnh)
 *   lv     cấp YCT (1-4)
 *   h      chữ Hán;  py: pinyin của từ
 *   vi/en  nghĩa tiếng Việt / tiếng Anh
 *   ex, exPy, exVi, exEn   cụm/câu ví dụ + pinyin + dịch (không có ở thẻ câu giao tiếp)
 *   tok, tokPy             các mảnh từ của câu ví dụ cho chế độ "Ghép câu"
 *                          (không có nếu ví dụ chỉ là 1 từ ghép)
 *   txt    1 = hình có in sẵn chữ Hán/câu ví dụ -> ẩn hình trước khi trả lời
 *          ở chế độ Ghép câu / Chọn chữ đúng để không lộ đáp án
 */

export const IMG_VERSION = '1';

export const CARDS = [
  {"id":"1-01-0","lv":1,"h":"爱","py":"ài","vi":"yêu","en":"love","ex":"我爱妈妈。","exPy":"Wǒ ài māma.","exVi":"Con yêu mẹ.","exEn":"I love mom.","tok":["我","爱","妈妈"],"tokPy":["wǒ","ài","māma"]},
  {"id":"1-01-1","lv":1,"h":"八","py":"bā","vi":"số tám","en":"eight","ex":"八个苹果","exPy":"bā ge píngguǒ","exVi":"tám quả táo","exEn":"eight apples","tok":["八","个","苹果"],"tokPy":["bā","ge","píngguǒ"]},
  {"id":"1-01-2","lv":1,"h":"爸爸","py":"bàba","vi":"bố","en":"dad","ex":"我的爸爸","exPy":"wǒ de bàba","exVi":"bố của tôi","exEn":"my dad","tok":["我","的","爸爸"],"tokPy":["wǒ","de","bàba"]},
  {"id":"1-01-3","lv":1,"h":"鼻子","py":"bízi","vi":"cái mũi","en":"nose","ex":"大鼻子","exPy":"dà bízi","exVi":"mũi to","exEn":"big nose","tok":["大","鼻子"],"tokPy":["dà","bízi"]},
  {"id":"1-02-0","lv":1,"h":"不","py":"bù","vi":"không","en":"no/not","ex":"不好","exPy":"bù hǎo","exVi":"không tốt","exEn":"not good","tok":["不","好"],"tokPy":["bù","hǎo"]},
  {"id":"1-02-1","lv":1,"h":"长","py":"cháng","vi":"dài","en":"long","ex":"长头发","exPy":"cháng tóufa","exVi":"tóc dài","exEn":"long hair","tok":["长","头发"],"tokPy":["cháng","tóufa"]},
  {"id":"1-02-2","lv":1,"h":"吃","py":"chī","vi":"ăn","en":"eat","ex":"吃米饭","exPy":"chī mǐfàn","exVi":"ăn cơm","exEn":"eat rice","tok":["吃","米饭"],"tokPy":["chī","mǐfàn"]},
  {"id":"1-02-3","lv":1,"h":"大","py":"dà","vi":"to, lớn","en":"big","ex":"大西瓜","exPy":"dà xīguā","exVi":"dưa hấu to","exEn":"big watermelons","tok":["大","西瓜"],"tokPy":["dà","xīguā"]},
  {"id":"1-03-0","lv":1,"h":"多","py":"duō","vi":"nhiều","en":"many/much","ex":"很多","exPy":"hěn duō","exVi":"rất nhiều","exEn":"so many/too much","tok":["很","多"],"tokPy":["hěn","duō"]},
  {"id":"1-03-1","lv":1,"h":"点","py":"diǎn","vi":"giờ","en":"o'clock","ex":"下午五点","exPy":"xiàwǔ wǔ diǎn","exVi":"năm giờ chiều","exEn":"five p.m.","tok":["下午","五点"],"tokPy":["xiàwǔ","wǔdiǎn"],"txt":1},
  {"id":"1-03-2","lv":1,"h":"耳朵","py":"ěrduo","vi":"cái tai","en":"ear","ex":"两个耳朵","exPy":"liǎng ge ěrduo","exVi":"hai cái tai","exEn":"two ears","tok":["两","个","耳朵"],"tokPy":["liǎng","ge","ěrduo"]},
  {"id":"1-03-3","lv":1,"h":"二","py":"èr","vi":"số hai","en":"two","ex":"第二","exPy":"dì'èr","exVi":"thứ hai","exEn":"second","tok":["第","二"],"tokPy":["dì","èr"]},
  {"id":"1-04-0","lv":1,"h":"高","py":"gāo","vi":"cao","en":"high","ex":"树很高。","exPy":"Shù hěn gāo.","exVi":"Cái cây rất cao.","exEn":"The tree is high.","tok":["树","很","高"],"tokPy":["shù","hěn","gāo"]},
  {"id":"1-04-1","lv":1,"h":"高兴","py":"gāoxìng","vi":"vui vẻ","en":"happy","ex":"我很高兴。","exPy":"Wǒ hěn gāoxìng.","exVi":"Tôi rất vui.","exEn":"I'm happy.","tok":["我","很","高兴"],"tokPy":["wǒ","hěn","gāoxìng"]},
  {"id":"1-04-2","lv":1,"h":"哥哥","py":"gēge","vi":"anh trai","en":"older brother","ex":"我和哥哥","exPy":"wǒ hé gēge","exVi":"tôi và anh trai","exEn":"my brother and I","tok":["我","和","哥哥"],"tokPy":["wǒ","hé","gēge"]},
  {"id":"1-04-3","lv":1,"h":"个","py":"gè","vi":"cái, chiếc (lượng từ)","en":"quantifier","ex":"一个苹果","exPy":"yí ge píngguǒ","exVi":"một quả táo","exEn":"an apple","tok":["一","个","苹果"],"tokPy":["yí","ge","píngguǒ"],"txt":1},
  {"id":"1-05-0","lv":1,"h":"个子","py":"gèzi","vi":"vóc dáng, chiều cao","en":"height","ex":"他个子很高。","exPy":"Tā gèzi hěn gāo.","exVi":"Anh ấy rất cao.","exEn":"He is tall.","tok":["他","个子","很","高"],"tokPy":["tā","gèzi","hěn","gāo"]},
  {"id":"1-05-1","lv":1,"h":"狗","py":"gǒu","vi":"con chó","en":"dog","ex":"狗和猫","exPy":"gǒu hé māo","exVi":"chó và mèo","exEn":"dogs and cats","tok":["狗","和","猫"],"tokPy":["gǒu","hé","māo"]},
  {"id":"1-05-2","lv":1,"h":"号","py":"hào","vi":"ngày (trong tháng)","en":"date","ex":"五月三号","exPy":"wǔ yuè sān hào","exVi":"ngày 3 tháng 5","exEn":"May third","tok":["五月","三号"],"tokPy":["wǔyuè","sānhào"]},
  {"id":"1-05-3","lv":1,"h":"喝","py":"hē","vi":"uống","en":"drink","ex":"喝水","exPy":"hē shuǐ","exVi":"uống nước","exEn":"drink water","tok":["喝","水"],"tokPy":["hē","shuǐ"]},
  {"id":"1-06-0","lv":1,"h":"和","py":"hé","vi":"và","en":"and","ex":"我和你","exPy":"wǒ hé nǐ","exVi":"tôi và bạn","exEn":"you and me","tok":["我","和","你"],"tokPy":["wǒ","hé","nǐ"],"txt":1},
  {"id":"1-06-1","lv":1,"h":"好","py":"hǎo","vi":"tốt, hay","en":"good","ex":"好朋友","exPy":"hǎo péngyou","exVi":"bạn tốt","exEn":"good friend","tok":["好","朋友"],"tokPy":["hǎo","péngyou"]},
  {"id":"1-06-2","lv":1,"h":"家","py":"jiā","vi":"nhà","en":"home","ex":"家庭","exPy":"jiātíng","exVi":"gia đình","exEn":"family"},
  {"id":"1-06-3","lv":1,"h":"叫","py":"jiào","vi":"gọi, tên là","en":"call","ex":"我叫豆豆。","exPy":"Wǒ jiào Dòudou.","exVi":"Tớ tên là Đậu Đậu.","exEn":"My name is Doudou.","tok":["我","叫","豆豆"],"tokPy":["wǒ","jiào","Dòudou"]},
  {"id":"1-07-0","lv":1,"h":"姐姐","py":"jiějie","vi":"chị gái","en":"elder sister","ex":"我和姐姐","exPy":"wǒ hé jiějie","exVi":"tôi và chị gái","exEn":"my sister and I","tok":["我","和","姐姐"],"tokPy":["wǒ","hé","jiějie"]},
  {"id":"1-07-1","lv":1,"h":"今天","py":"jīntiān","vi":"hôm nay","en":"today","ex":"今天星期一。","exPy":"Jīntiān xīngqīyī.","exVi":"Hôm nay là thứ Hai.","exEn":"Today is Monday.","tok":["今天","星期一"],"tokPy":["jīntiān","xīngqīyī"]},
  {"id":"1-07-2","lv":1,"h":"九","py":"jiǔ","vi":"số chín","en":"nine","ex":"九年","exPy":"jiǔ nián","exVi":"chín năm","exEn":"nine years","tok":["九","年"],"tokPy":["jiǔ","nián"]},
  {"id":"1-07-3","lv":1,"h":"看","py":"kàn","vi":"nhìn, xem","en":"look/watch","ex":"看电视","exPy":"kàn diànshì","exVi":"xem tivi","exEn":"watch TV","tok":["看","电视"],"tokPy":["kàn","diànshì"]},
  {"id":"1-08-0","lv":1,"h":"口","py":"kǒu","vi":"miệng","en":"mouth","ex":"张口","exPy":"zhāng kǒu","exVi":"há miệng","exEn":"open your mouth","tok":["张","口"],"tokPy":["zhāng","kǒu"]},
  {"id":"1-08-1","lv":1,"h":"老师","py":"lǎoshī","vi":"thầy giáo, cô giáo","en":"teacher","ex":"我是老师。","exPy":"Wǒ shì lǎoshī.","exVi":"Tôi là giáo viên.","exEn":"I am a teacher.","tok":["我","是","老师"],"tokPy":["wǒ","shì","lǎoshī"]},
  {"id":"1-08-2","lv":1,"h":"六","py":"liù","vi":"số sáu","en":"six","ex":"六岁","exPy":"liù suì","exVi":"sáu tuổi","exEn":"six years old","tok":["六","岁"],"tokPy":["liù","suì"]},
  {"id":"1-08-3","lv":1,"h":"妈妈","py":"māma","vi":"mẹ","en":"mom","ex":"我的妈妈","exPy":"wǒ de māma","exVi":"mẹ của tôi","exEn":"my mom","tok":["我","的","妈妈"],"tokPy":["wǒ","de","māma"]},
  {"id":"1-09-0","lv":1,"h":"猫","py":"māo","vi":"con mèo","en":"cat","ex":"一只猫","exPy":"yì zhī māo","exVi":"một con mèo","exEn":"a cat","tok":["一","只","猫"],"tokPy":["yì","zhī","māo"]},
  {"id":"1-09-1","lv":1,"h":"米饭","py":"mǐfàn","vi":"cơm","en":"rice","ex":"吃米饭","exPy":"chī mǐfàn","exVi":"ăn cơm","exEn":"eat rice","tok":["吃","米饭"],"tokPy":["chī","mǐfàn"]},
  {"id":"1-09-2","lv":1,"h":"面条","py":"miàntiáo","vi":"mì sợi","en":"noodle","ex":"吃面条","exPy":"chī miàntiáo","exVi":"ăn mì","exEn":"eat noodles","tok":["吃","面条"],"tokPy":["chī","miàntiáo"]},
  {"id":"1-09-3","lv":1,"h":"明天","py":"míngtiān","vi":"ngày mai","en":"tomorrow","ex":"明天星期四。","exPy":"Míngtiān xīngqīsì.","exVi":"Ngày mai là thứ Năm.","exEn":"Tomorrow is Thursday.","tok":["明天","星期四"],"tokPy":["míngtiān","xīngqīsì"]},
  {"id":"1-10-0","lv":1,"h":"哪儿","py":"nǎr","vi":"ở đâu","en":"where","ex":"你在哪儿？","exPy":"Nǐ zài nǎr?","exVi":"Bạn ở đâu?","exEn":"Where are you?","tok":["你","在","哪儿"],"tokPy":["nǐ","zài","nǎr"]},
  {"id":"1-10-1","lv":1,"h":"那儿","py":"nàr","vi":"ở đó, chỗ kia","en":"there","ex":"他在那儿。","exPy":"Tā zài nàr.","exVi":"Anh ấy ở đằng kia.","exEn":"There he is.","tok":["他","在","那儿"],"tokPy":["tā","zài","nàr"]},
  {"id":"1-10-2","lv":1,"h":"你","py":"nǐ","vi":"bạn","en":"you","ex":"你是谁？","exPy":"Nǐ shì shéi?","exVi":"Bạn là ai?","exEn":"Who are you?","tok":["你","是","谁"],"tokPy":["nǐ","shì","shéi"]},
  {"id":"1-10-3","lv":1,"h":"鸟","py":"niǎo","vi":"con chim","en":"bird","ex":"一只鸟","exPy":"yì zhī niǎo","exVi":"một con chim","exEn":"a bird","tok":["一","只","鸟"],"tokPy":["yì","zhī","niǎo"]},
  {"id":"1-11-0","lv":1,"h":"牛奶","py":"niúnǎi","vi":"sữa bò","en":"milk","ex":"喝牛奶","exPy":"hē niúnǎi","exVi":"uống sữa","exEn":"drink milk","tok":["喝","牛奶"],"tokPy":["hē","niúnǎi"]},
  {"id":"1-11-1","lv":1,"h":"苹果","py":"píngguǒ","vi":"quả táo","en":"apple","ex":"吃苹果","exPy":"chī píngguǒ","exVi":"ăn táo","exEn":"eat apple","tok":["吃","苹果"],"tokPy":["chī","píngguǒ"]},
  {"id":"1-11-2","lv":1,"h":"七","py":"qī","vi":"số bảy","en":"seven","ex":"七岁","exPy":"qī suì","exVi":"bảy tuổi","exEn":"seven years old","tok":["七","岁"],"tokPy":["qī","suì"]},
  {"id":"1-11-3","lv":1,"h":"去","py":"qù","vi":"đi","en":"go","ex":"去学校","exPy":"qù xuéxiào","exVi":"đi đến trường","exEn":"go to school","tok":["去","学校"],"tokPy":["qù","xuéxiào"]},
  {"id":"1-12-0","lv":1,"h":"认识","py":"rènshi","vi":"quen biết","en":"know","ex":"我认识你。","exPy":"Wǒ rènshi nǐ.","exVi":"Tôi biết bạn.","exEn":"I know you.","tok":["我","认识","你"],"tokPy":["wǒ","rènshi","nǐ"]},
  {"id":"1-12-1","lv":1,"h":"三","py":"sān","vi":"số ba","en":"three","ex":"三个人","exPy":"sān ge rén","exVi":"ba người","exEn":"three people","tok":["三","个","人"],"tokPy":["sān","ge","rén"]},
  {"id":"1-12-2","lv":1,"h":"商店","py":"shāngdiàn","vi":"cửa hàng","en":"store","ex":"商店在这儿。","exPy":"Shāngdiàn zài zhèr.","exVi":"Cửa hàng ở đây.","exEn":"Store is here.","tok":["商店","在","这儿"],"tokPy":["shāngdiàn","zài","zhèr"]},
  {"id":"1-12-3","lv":1,"h":"十","py":"shí","vi":"số mười","en":"ten","ex":"十个人","exPy":"shí ge rén","exVi":"mười người","exEn":"ten people","tok":["十","个","人"],"tokPy":["shí","ge","rén"]},
  {"id":"1-13-0","lv":1,"h":"手","py":"shǒu","vi":"bàn tay","en":"hand","ex":"手指","exPy":"shǒuzhǐ","exVi":"ngón tay","exEn":"finger"},
  {"id":"1-13-1","lv":1,"h":"水","py":"shuǐ","vi":"nước","en":"water","ex":"喝水","exPy":"hē shuǐ","exVi":"uống nước","exEn":"drink water","tok":["喝","水"],"tokPy":["hē","shuǐ"]},
  {"id":"1-13-2","lv":1,"h":"四","py":"sì","vi":"số bốn","en":"four","ex":"四年","exPy":"sì nián","exVi":"bốn năm","exEn":"four years","tok":["四","年"],"tokPy":["sì","nián"]},
  {"id":"1-13-3","lv":1,"h":"岁","py":"suì","vi":"tuổi","en":"years of age","ex":"四岁","exPy":"sì suì","exVi":"bốn tuổi","exEn":"four years old","tok":["四","岁"],"tokPy":["sì","suì"]},
  {"id":"1-14-0","lv":1,"h":"她","py":"tā","vi":"cô ấy","en":"she","ex":"她是贝贝。","exPy":"Tā shì Bèibei.","exVi":"Cô ấy là Bối Bối.","exEn":"She is Beibei.","tok":["她","是","贝贝"],"tokPy":["tā","shì","Bèibei"]},
  {"id":"1-14-1","lv":1,"h":"他","py":"tā","vi":"anh ấy, cậu ấy","en":"he","ex":"他是小豪。","exPy":"Tā shì Xiǎoháo.","exVi":"Cậu ấy là Tiểu Hào.","exEn":"He is Xiaohao.","tok":["他","是","小豪"],"tokPy":["tā","shì","Xiǎoháo"]},
  {"id":"1-14-2","lv":1,"h":"头发","py":"tóufa","vi":"tóc","en":"hair","ex":"长头发","exPy":"cháng tóufa","exVi":"tóc dài","exEn":"long hair","tok":["长","头发"],"tokPy":["cháng","tóufa"]},
  {"id":"1-14-3","lv":1,"h":"喜欢","py":"xǐhuan","vi":"thích","en":"like","ex":"喜欢看书","exPy":"xǐhuan kàn shū","exVi":"thích đọc sách","exEn":"like to read","tok":["喜欢","看","书"],"tokPy":["xǐhuan","kàn","shū"]},
  {"id":"1-15-0","lv":1,"h":"现在","py":"xiànzài","vi":"bây giờ","en":"now","ex":"现在开始","exPy":"xiànzài kāishǐ","exVi":"bắt đầu từ bây giờ","exEn":"starting now","tok":["现在","开始"],"tokPy":["xiànzài","kāishǐ"]},
  {"id":"1-15-1","lv":1,"h":"小","py":"xiǎo","vi":"nhỏ, bé","en":"small/little","ex":"小狗","exPy":"xiǎo gǒu","exVi":"chó con","exEn":"puppy","tok":["小","狗"],"tokPy":["xiǎo","gǒu"]},
  {"id":"1-15-2","lv":1,"h":"谢谢","py":"xièxie","vi":"cảm ơn","en":"thanks","ex":"谢谢你！","exPy":"Xièxie nǐ!","exVi":"Cảm ơn bạn!","exEn":"Thank you!","tok":["谢谢","你"],"tokPy":["xièxie","nǐ"],"txt":1},
  {"id":"1-15-3","lv":1,"h":"星期","py":"xīngqī","vi":"tuần, thứ","en":"week","ex":"星期一","exPy":"xīngqīyī","exVi":"thứ Hai","exEn":"Monday","tok":["星期","一"],"tokPy":["xīngqī","yī"]},
  {"id":"1-16-0","lv":1,"h":"学校","py":"xuéxiào","vi":"trường học","en":"school","ex":"去学校","exPy":"qù xuéxiào","exVi":"đi đến trường","exEn":"go to school","tok":["去","学校"],"tokPy":["qù","xuéxiào"]},
  {"id":"1-16-1","lv":1,"h":"眼睛","py":"yǎnjing","vi":"mắt","en":"eye","ex":"小眼睛","exPy":"xiǎo yǎnjing","exVi":"mắt nhỏ","exEn":"small eyes","tok":["小","眼睛"],"tokPy":["xiǎo","yǎnjing"]},
  {"id":"1-16-2","lv":1,"h":"一","py":"yī","vi":"số một","en":"one","ex":"第一天","exPy":"dì yī tiān","exVi":"ngày đầu tiên","exEn":"day one","tok":["第一","天"],"tokPy":["dìyī","tiān"]},
  {"id":"1-16-3","lv":1,"h":"有","py":"yǒu","vi":"có","en":"have","ex":"没有","exPy":"méiyǒu","exVi":"không có","exEn":"none","tok":["没","有"],"tokPy":["méi","yǒu"]},
  {"id":"1-17-0","lv":1,"h":"鱼","py":"yú","vi":"con cá","en":"fish","ex":"钓鱼","exPy":"diàoyú","exVi":"câu cá","exEn":"fishing","tok":["钓","鱼"],"tokPy":["diào","yú"]},
  {"id":"1-17-1","lv":1,"h":"再见","py":"zàijiàn","vi":"tạm biệt","en":"goodbye","ex":"老师再见！","exPy":"Lǎoshī zàijiàn!","exVi":"Chào tạm biệt thầy cô!","exEn":"Goodbye teacher!","tok":["老师","再见"],"tokPy":["lǎoshī","zàijiàn"]},
  {"id":"1-17-2","lv":1,"h":"这儿","py":"zhèr","vi":"ở đây","en":"here","ex":"猫在这儿。","exPy":"Māo zài zhèr.","exVi":"Con mèo ở đây.","exEn":"The cat is here.","tok":["猫","在","这儿"],"tokPy":["māo","zài","zhèr"]},
  {"id":"1-17-3","lv":1,"h":"中国人","py":"Zhōngguórén","vi":"người Trung Quốc","en":"Chinese","ex":"我是中国人。","exPy":"Wǒ shì Zhōngguórén.","exVi":"Tôi là người Trung Quốc.","exEn":"I'm Chinese.","tok":["我","是","中国人"],"tokPy":["wǒ","shì","Zhōngguórén"]},
  {"id":"1-18-0","lv":1,"h":"我","py":"wǒ","vi":"tôi, tớ","en":"I/me","ex":"我是老师。","exPy":"Wǒ shì lǎoshī.","exVi":"Tôi là giáo viên.","exEn":"I'm a teacher.","tok":["我","是","老师"],"tokPy":["wǒ","shì","lǎoshī"]},
  {"id":"1-18-1","lv":1,"h":"我们","py":"wǒmen","vi":"chúng tôi, chúng ta","en":"we/us","ex":"我们是学生。","exPy":"Wǒmen shì xuésheng.","exVi":"Chúng tôi là học sinh.","exEn":"We're students.","tok":["我们","是","学生"],"tokPy":["wǒmen","shì","xuésheng"]},
  {"id":"1-18-2","lv":1,"h":"五","py":"wǔ","vi":"số năm","en":"five","ex":"五点","exPy":"wǔ diǎn","exVi":"năm giờ","exEn":"five o'clock","tok":["五","点"],"tokPy":["wǔ","diǎn"]},
  {"id":"1-18-3","lv":1,"h":"月","py":"yuè","vi":"tháng","en":"month","ex":"五月","exPy":"wǔ yuè","exVi":"tháng Năm","exEn":"May","tok":["五","月"],"tokPy":["wǔ","yuè"]},
  {"id":"1-19-0","lv":1,"h":"是","py":"shì","vi":"là","en":"am/is/are","ex":"我是学生。","exPy":"Wǒ shì xuésheng.","exVi":"Tôi là học sinh.","exEn":"I'm a student.","tok":["我","是","学生"],"tokPy":["wǒ","shì","xuésheng"],"txt":1},
  {"id":"1-19-1","lv":1,"h":"在","py":"zài","vi":"ở, tại","en":"in/on","ex":"我在中国。","exPy":"Wǒ zài Zhōngguó.","exVi":"Tôi đang ở Trung Quốc.","exEn":"I'm in China.","tok":["我","在","中国"],"tokPy":["wǒ","zài","Zhōngguó"],"txt":1},
  {"id":"1-19-2","lv":1,"h":"谁","py":"shéi","vi":"ai","en":"who","ex":"你是谁？","exPy":"Nǐ shì shéi?","exVi":"Bạn là ai?","exEn":"Who are you?","tok":["你","是","谁"],"tokPy":["nǐ","shì","shéi"],"txt":1},
  {"id":"1-19-3","lv":1,"h":"什么","py":"shénme","vi":"cái gì","en":"what","ex":"那是什么？","exPy":"Nà shì shénme?","exVi":"Kia là cái gì?","exEn":"What's that?","tok":["那","是","什么"],"tokPy":["nà","shì","shénme"],"txt":1},
  {"id":"1-20-0","lv":1,"h":"的","py":"de","vi":"của (trợ từ)","en":"auxiliary word","ex":"绿色的苹果","exPy":"lǜsè de píngguǒ","exVi":"quả táo màu xanh","exEn":"green apples","tok":["绿色","的","苹果"],"tokPy":["lǜsè","de","píngguǒ"],"txt":1},
  {"id":"1-20-1","lv":1,"h":"很","py":"hěn","vi":"rất","en":"very (before adjectives)","ex":"西瓜很大。","exPy":"Xīguā hěn dà.","exVi":"Quả dưa hấu rất to.","exEn":"The watermelon is big.","tok":["西瓜","很","大"],"tokPy":["xīguā","hěn","dà"],"txt":1},
  {"id":"1-20-2","lv":1,"h":"几","py":"jǐ","vi":"mấy","en":"how many","ex":"你家有几口人？","exPy":"Nǐ jiā yǒu jǐ kǒu rén?","exVi":"Nhà bạn có mấy người?","exEn":"How many people are there in your family?","tok":["你","家","有","几","口","人"],"tokPy":["nǐ","jiā","yǒu","jǐ","kǒu","rén"]},
  {"id":"1-20-3","lv":1,"h":"吗","py":"ma","vi":"không? (trợ từ hỏi)","en":"interrogative word","ex":"你吃饭了吗？","exPy":"Nǐ chīfàn le ma?","exVi":"Bạn ăn cơm chưa?","exEn":"Did you have a meal?","tok":["你","吃饭","了","吗"],"tokPy":["nǐ","chīfàn","le","ma"],"txt":1},
  {"id":"2-01-0","lv":2,"h":"包子","py":"bāozi","vi":"bánh bao","en":"steamed bun","ex":"吃包子","exPy":"chī bāozi","exVi":"ăn bánh bao","exEn":"eat steamed bun","tok":["吃","包子"],"tokPy":["chī","bāozi"]},
  {"id":"2-01-1","lv":2,"h":"北京","py":"Běijīng","vi":"Bắc Kinh","en":"Beijing","ex":"我在北京。","exPy":"Wǒ zài Běijīng.","exVi":"Tôi đang ở Bắc Kinh.","exEn":"I am in Beijing.","tok":["我","在","北京"],"tokPy":["wǒ","zài","Běijīng"]},
  {"id":"2-01-2","lv":2,"h":"不客气","py":"Bú kèqi","vi":"Không có gì!","en":"You are welcome!","txt":1},
  {"id":"2-01-3","lv":2,"h":"茶","py":"chá","vi":"trà","en":"tea","ex":"喝茶","exPy":"hē chá","exVi":"uống trà","exEn":"drink tea","tok":["喝","茶"],"tokPy":["hē","chá"]},
  {"id":"2-02-0","lv":2,"h":"打电话","py":"dǎ diànhuà","vi":"gọi điện thoại","en":"make a phone call","ex":"给我打电话。","exPy":"Gěi wǒ dǎ diànhuà.","exVi":"Gọi điện cho tôi nhé.","exEn":"Make a phone call to me.","tok":["给","我","打","电话"],"tokPy":["gěi","wǒ","dǎ","diànhuà"]},
  {"id":"2-02-1","lv":2,"h":"电视","py":"diànshì","vi":"tivi","en":"TV","ex":"买电视","exPy":"mǎi diànshì","exVi":"mua tivi","exEn":"buy a TV","tok":["买","电视"],"tokPy":["mǎi","diànshì"]},
  {"id":"2-02-2","lv":2,"h":"对不起","py":"Duìbuqǐ","vi":"Xin lỗi!","en":"Sorry!","txt":1},
  {"id":"2-02-3","lv":2,"h":"弟弟","py":"dìdi","vi":"em trai","en":"younger brother","ex":"我的弟弟","exPy":"wǒ de dìdi","exVi":"em trai của tôi","exEn":"my younger brother","tok":["我","的","弟弟"],"tokPy":["wǒ","de","dìdi"]},
  {"id":"2-03-0","lv":2,"h":"房间","py":"fángjiān","vi":"căn phòng","en":"room","ex":"我的房间","exPy":"wǒ de fángjiān","exVi":"phòng của tôi","exEn":"my room","tok":["我","的","房间"],"tokPy":["wǒ","de","fángjiān"]},
  {"id":"2-03-1","lv":2,"h":"分钟","py":"fēnzhōng","vi":"phút","en":"minute","ex":"十分钟","exPy":"shí fēnzhōng","exVi":"mười phút","exEn":"ten minutes","tok":["十","分钟"],"tokPy":["shí","fēnzhōng"]},
  {"id":"2-03-2","lv":2,"h":"汉语","py":"Hànyǔ","vi":"tiếng Hán, tiếng Trung","en":"Chinese","ex":"说汉语","exPy":"shuō Hànyǔ","exVi":"nói tiếng Trung","exEn":"speak Chinese","tok":["说","汉语"],"tokPy":["shuō","Hànyǔ"],"txt":1},
  {"id":"2-03-3","lv":2,"h":"红","py":"hóng","vi":"màu đỏ","en":"red","ex":"红苹果","exPy":"hóng píngguǒ","exVi":"táo đỏ","exEn":"red apples","tok":["红","苹果"],"tokPy":["hóng","píngguǒ"]},
  {"id":"2-04-0","lv":2,"h":"画","py":"huà","vi":"vẽ, bức tranh","en":"draw/picture","ex":"画画儿","exPy":"huà huàr","exVi":"vẽ tranh","exEn":"draw a picture","tok":["画","画儿"],"tokPy":["huà","huàr"]},
  {"id":"2-04-1","lv":2,"h":"黄","py":"huáng","vi":"màu vàng","en":"yellow","ex":"黄色的叶子","exPy":"huángsè de yèzi","exVi":"lá màu vàng","exEn":"yellow leaves","tok":["黄色","的","叶子"],"tokPy":["huángsè","de","yèzi"]},
  {"id":"2-04-2","lv":2,"h":"好吃","py":"hǎochī","vi":"ngon","en":"delicious","ex":"面包很好吃。","exPy":"Miànbāo hěn hǎochī.","exVi":"Bánh mì rất ngon.","exEn":"The bread is delicious.","tok":["面包","很","好吃"],"tokPy":["miànbāo","hěn","hǎochī"]},
  {"id":"2-04-3","lv":2,"h":"脚","py":"jiǎo","vi":"bàn chân","en":"foot","ex":"一只脚","exPy":"yì zhī jiǎo","exVi":"một bàn chân","exEn":"a foot","tok":["一","只","脚"],"tokPy":["yì","zhī","jiǎo"]},
  {"id":"2-05-0","lv":2,"h":"可以","py":"kěyǐ","vi":"có thể","en":"can/may","ex":"你可以睡觉。","exPy":"Nǐ kěyǐ shuìjiào.","exVi":"Bạn có thể đi ngủ.","exEn":"You can sleep.","tok":["你","可以","睡觉"],"tokPy":["nǐ","kěyǐ","shuìjiào"]},
  {"id":"2-05-1","lv":2,"h":"来","py":"lái","vi":"đến, lại","en":"come","ex":"过来","exPy":"guòlai","exVi":"lại đây","exEn":"come here"},
  {"id":"2-05-2","lv":2,"h":"冷","py":"lěng","vi":"lạnh","en":"cold","ex":"天气很冷。","exPy":"Tiānqì hěn lěng.","exVi":"Thời tiết rất lạnh.","exEn":"The weather is cold.","tok":["天气","很","冷"],"tokPy":["tiānqì","hěn","lěng"]},
  {"id":"2-05-3","lv":2,"h":"里面","py":"lǐmiàn","vi":"bên trong","en":"inside","ex":"在房间里面","exPy":"zài fángjiān lǐmiàn","exVi":"ở trong phòng","exEn":"inside the room","tok":["在","房间","里面"],"tokPy":["zài","fángjiān","lǐmiàn"]},
  {"id":"2-06-0","lv":2,"h":"两","py":"liǎng","vi":"hai (dùng với lượng từ)","en":"two","ex":"两个西瓜","exPy":"liǎng ge xīguā","exVi":"hai quả dưa hấu","exEn":"two watermelons","tok":["两","个","西瓜"],"tokPy":["liǎng","ge","xīguā"]},
  {"id":"2-06-1","lv":2,"h":"绿","py":"lǜ","vi":"màu xanh lá","en":"green","ex":"绿苹果","exPy":"lǜ píngguǒ","exVi":"táo xanh","exEn":"green apples","tok":["绿","苹果"],"tokPy":["lǜ","píngguǒ"]},
  {"id":"2-06-2","lv":2,"h":"没关系","py":"Méi guānxi","vi":"Không sao đâu!","en":"That's all right!","txt":1},
  {"id":"2-06-3","lv":2,"h":"没有","py":"méiyǒu","vi":"không có","en":"none/no","ex":"没有人","exPy":"méiyǒu rén","exVi":"không có ai","exEn":"nobody","tok":["没有","人"],"tokPy":["méiyǒu","rén"]},
  {"id":"2-07-0","lv":2,"h":"妹妹","py":"mèimei","vi":"em gái","en":"younger sister","ex":"我和妹妹","exPy":"wǒ hé mèimei","exVi":"tôi và em gái","exEn":"younger sister and I","tok":["我","和","妹妹"],"tokPy":["wǒ","hé","mèimei"]},
  {"id":"2-07-1","lv":2,"h":"名字","py":"míngzi","vi":"tên","en":"name","ex":"我的名字","exPy":"wǒ de míngzi","exVi":"tên của tôi","exEn":"my name","tok":["我","的","名字"],"tokPy":["wǒ","de","míngzi"]},
  {"id":"2-07-2","lv":2,"h":"买","py":"mǎi","vi":"mua","en":"buy","ex":"买水果","exPy":"mǎi shuǐguǒ","exVi":"mua hoa quả","exEn":"buy fruits","tok":["买","水果"],"tokPy":["mǎi","shuǐguǒ"]},
  {"id":"2-07-3","lv":2,"h":"年","py":"nián","vi":"năm","en":"year","ex":"今年","exPy":"jīnnián","exVi":"năm nay","exEn":"this year"},
  {"id":"2-08-0","lv":2,"h":"朋友","py":"péngyou","vi":"bạn bè","en":"friend","ex":"好朋友","exPy":"hǎo péngyou","exVi":"bạn tốt","exEn":"good friend","tok":["好","朋友"],"tokPy":["hǎo","péngyou"]},
  {"id":"2-08-1","lv":2,"h":"起床","py":"qǐchuáng","vi":"thức dậy","en":"get up","ex":"七点起床","exPy":"qī diǎn qǐchuáng","exVi":"dậy lúc bảy giờ","exEn":"get up at seven o'clock","tok":["七点","起床"],"tokPy":["qīdiǎn","qǐchuáng"]},
  {"id":"2-08-2","lv":2,"h":"铅笔","py":"qiānbǐ","vi":"bút chì","en":"pencil","ex":"我有铅笔。","exPy":"Wǒ yǒu qiānbǐ.","exVi":"Tôi có bút chì.","exEn":"I have a pencil.","tok":["我","有","铅笔"],"tokPy":["wǒ","yǒu","qiānbǐ"]},
  {"id":"2-08-3","lv":2,"h":"钱","py":"qián","vi":"tiền","en":"money","ex":"有很多钱","exPy":"yǒu hěn duō qián","exVi":"có rất nhiều tiền","exEn":"have a lot of money","tok":["有","很多","钱"],"tokPy":["yǒu","hěnduō","qián"]},
  {"id":"2-09-0","lv":2,"h":"热","py":"rè","vi":"nóng","en":"hot","ex":"天气真热！","exPy":"Tiānqì zhēn rè!","exVi":"Thời tiết nóng quá!","exEn":"The weather is really hot!","tok":["天气","真","热"],"tokPy":["tiānqì","zhēn","rè"]},
  {"id":"2-09-1","lv":2,"h":"上边","py":"shàngbian","vi":"phía trên","en":"upside/on","ex":"在桌子上边","exPy":"zài zhuōzi shàngbian","exVi":"ở trên bàn","exEn":"on the table","tok":["在","桌子","上边"],"tokPy":["zài","zhuōzi","shàngbian"]},
  {"id":"2-09-2","lv":2,"h":"书包","py":"shūbāo","vi":"cặp sách","en":"schoolbag","ex":"买书包","exPy":"mǎi shūbāo","exVi":"mua cặp sách","exEn":"buy a schoolbag","tok":["买","书包"],"tokPy":["mǎi","shūbāo"]},
  {"id":"2-09-3","lv":2,"h":"睡觉","py":"shuìjiào","vi":"đi ngủ","en":"sleep","ex":"我想睡觉。","exPy":"Wǒ xiǎng shuìjiào.","exVi":"Tôi muốn đi ngủ.","exEn":"I want to sleep.","tok":["我","想","睡觉"],"tokPy":["wǒ","xiǎng","shuìjiào"]},
  {"id":"2-10-0","lv":2,"h":"说话","py":"shuōhuà","vi":"nói chuyện","en":"talk","ex":"和爸爸说话","exPy":"hé bàba shuōhuà","exVi":"nói chuyện với bố","exEn":"talk to dad","tok":["和","爸爸","说话"],"tokPy":["hé","bàba","shuōhuà"]},
  {"id":"2-10-1","lv":2,"h":"天气","py":"tiānqì","vi":"thời tiết","en":"weather","ex":"天气不好。","exPy":"Tiānqì bù hǎo.","exVi":"Thời tiết không tốt.","exEn":"The weather is not good.","tok":["天气","不好"],"tokPy":["tiānqì","bùhǎo"]},
  {"id":"2-10-2","lv":2,"h":"同学","py":"tóngxué","vi":"bạn cùng lớp","en":"classmate","ex":"我的同学","exPy":"wǒ de tóngxué","exVi":"bạn cùng lớp của tôi","exEn":"my classmate","tok":["我","的","同学"],"tokPy":["wǒ","de","tóngxué"]},
  {"id":"2-10-3","lv":2,"h":"玩","py":"wán","vi":"chơi","en":"play","ex":"玩游戏","exPy":"wán yóuxì","exVi":"chơi trò chơi","exEn":"play games","tok":["玩","游戏"],"tokPy":["wán","yóuxì"]},
  {"id":"2-11-0","lv":2,"h":"晚上","py":"wǎnshang","vi":"buổi tối","en":"night","ex":"昨天晚上","exPy":"zuótiān wǎnshang","exVi":"tối hôm qua","exEn":"last night","tok":["昨天","晚上"],"tokPy":["zuótiān","wǎnshang"]},
  {"id":"2-11-1","lv":2,"h":"香蕉","py":"xiāngjiāo","vi":"quả chuối","en":"banana","ex":"吃香蕉","exPy":"chī xiāngjiāo","exVi":"ăn chuối","exEn":"eat bananas","tok":["吃","香蕉"],"tokPy":["chī","xiāngjiāo"]},
  {"id":"2-11-2","lv":2,"h":"熊猫","py":"xióngmāo","vi":"gấu trúc","en":"panda","ex":"大熊猫","exPy":"dà xióngmāo","exVi":"gấu trúc lớn","exEn":"giant panda","tok":["大","熊猫"],"tokPy":["dà","xióngmāo"]},
  {"id":"2-11-3","lv":2,"h":"学生","py":"xuésheng","vi":"học sinh","en":"student","ex":"学生和老师","exPy":"xuésheng hé lǎoshī","exVi":"học sinh và giáo viên","exEn":"student and teacher","tok":["学生","和","老师"],"tokPy":["xuésheng","hé","lǎoshī"]},
  {"id":"2-12-0","lv":2,"h":"学习","py":"xuéxí","vi":"học tập","en":"study/learn","ex":"学习汉语","exPy":"xuéxí Hànyǔ","exVi":"học tiếng Trung","exEn":"learn Chinese","tok":["学习","汉语"],"tokPy":["xuéxí","Hànyǔ"]},
  {"id":"2-12-1","lv":2,"h":"颜色","py":"yánsè","vi":"màu sắc","en":"color","ex":"花的颜色","exPy":"huā de yánsè","exVi":"màu của bông hoa","exEn":"the color of the flower","tok":["花","的","颜色"],"tokPy":["huā","de","yánsè"]},
  {"id":"2-12-2","lv":2,"h":"医生","py":"yīshēng","vi":"bác sĩ","en":"doctor","ex":"我是医生。","exPy":"Wǒ shì yīshēng.","exVi":"Tôi là bác sĩ.","exEn":"I'm a doctor.","tok":["我","是","医生"],"tokPy":["wǒ","shì","yīshēng"]},
  {"id":"2-12-3","lv":2,"h":"医院","py":"yīyuàn","vi":"bệnh viện","en":"hospital","ex":"去医院","exPy":"qù yīyuàn","exVi":"đi bệnh viện","exEn":"go to hospital","tok":["去","医院"],"tokPy":["qù","yīyuàn"]},
  {"id":"2-13-0","lv":2,"h":"椅子","py":"yǐzi","vi":"cái ghế","en":"chair","ex":"坐在椅子上","exPy":"zuò zài yǐzi shàng","exVi":"ngồi trên ghế","exEn":"sit on the chair","tok":["坐","在","椅子","上"],"tokPy":["zuò","zài","yǐzi","shàng"]},
  {"id":"2-13-1","lv":2,"h":"早上","py":"zǎoshang","vi":"buổi sáng","en":"morning","ex":"早上好！","exPy":"Zǎoshang hǎo!","exVi":"Chào buổi sáng!","exEn":"Good morning!","tok":["早上","好"],"tokPy":["zǎoshang","hǎo"]},
  {"id":"2-13-2","lv":2,"h":"只","py":"zhī","vi":"con (lượng từ cho con vật)","en":"quantifier","ex":"一只羊","exPy":"yì zhī yáng","exVi":"một con cừu","exEn":"one sheep","tok":["一","只","羊"],"tokPy":["yì","zhī","yáng"],"txt":1},
  {"id":"2-13-3","lv":2,"h":"桌子","py":"zhuōzi","vi":"cái bàn","en":"table","ex":"在桌子下边","exPy":"zài zhuōzi xiàbian","exVi":"ở dưới gầm bàn","exEn":"under the table","tok":["在","桌子","下边"],"tokPy":["zài","zhuōzi","xiàbian"]},
  {"id":"2-14-0","lv":2,"h":"昨天","py":"zuótiān","vi":"hôm qua","en":"yesterday","ex":"昨天星期四。","exPy":"Zuótiān xīngqīsì.","exVi":"Hôm qua là thứ Năm.","exEn":"Yesterday is Thursday.","tok":["昨天","星期四"],"tokPy":["zuótiān","xīngqīsì"]},
  {"id":"2-14-1","lv":2,"h":"坐","py":"zuò","vi":"ngồi","en":"sit","ex":"坐下","exPy":"zuò xia","exVi":"ngồi xuống","exEn":"sit down","tok":["坐","下"],"tokPy":["zuò","xia"]},
  {"id":"2-14-2","lv":2,"h":"字","py":"zì","vi":"chữ","en":"character","ex":"汉字","exPy":"Hànzì","exVi":"chữ Hán","exEn":"Chinese characters","txt":1},
  {"id":"2-14-3","lv":2,"h":"块","py":"kuài","vi":"đồng (đơn vị tiền)","en":"quantifier for price","ex":"十块","exPy":"shí kuài","exVi":"mười đồng","exEn":"ten dollars","tok":["十","块"],"tokPy":["shí","kuài"],"txt":1},
  {"id":"2-15-0","lv":2,"h":"漂亮","py":"piàoliang","vi":"xinh đẹp","en":"beautiful","ex":"妈妈很漂亮。","exPy":"Māma hěn piàoliang.","exVi":"Mẹ rất xinh đẹp.","exEn":"Mom is beautiful.","tok":["妈妈","很","漂亮"],"tokPy":["māma","hěn","piàoliang"]},
  {"id":"2-15-1","lv":2,"h":"比","py":"bǐ","vi":"so với, hơn","en":"than","ex":"西瓜比苹果大。","exPy":"Xīguā bǐ píngguǒ dà.","exVi":"Dưa hấu to hơn quả táo.","exEn":"The watermelon is bigger than the apple.","tok":["西瓜","比","苹果","大"],"tokPy":["xīguā","bǐ","píngguǒ","dà"],"txt":1},
  {"id":"2-15-2","lv":2,"h":"多少","py":"duōshao","vi":"bao nhiêu","en":"how much/how many","ex":"这个多少钱？","exPy":"Zhège duōshǎo qián?","exVi":"Cái này bao nhiêu tiền?","exEn":"How much is it?","tok":["这个","多少钱"],"tokPy":["zhège","duōshǎoqián"],"txt":1},
  {"id":"2-15-3","lv":2,"h":"觉得","py":"juéde","vi":"cảm thấy","en":"feel","ex":"我觉得很冷！","exPy":"Wǒ juéde hěn lěng!","exVi":"Tôi thấy lạnh quá!","exEn":"I feel cold!","tok":["我","觉得","很","冷"],"tokPy":["wǒ","juéde","hěn","lěng"],"txt":1},
  {"id":"2-16-0","lv":2,"h":"了","py":"le","vi":"rồi (trợ từ)","en":"grammatical particle","ex":"回家了。","exPy":"Huíjiā le.","exVi":"Về nhà rồi.","exEn":"Go back home.","tok":["回家","了"],"tokPy":["huíjiā","le"],"txt":1},
  {"id":"2-16-1","lv":2,"h":"呢","py":"ne","vi":"đang... (trợ từ)","en":"grammatical particle","ex":"他在睡觉呢。","exPy":"Tā zài shuìjiào ne.","exVi":"Cậu ấy đang ngủ.","exEn":"He is sleeping.","tok":["他","在","睡觉","呢"],"tokPy":["tā","zài","shuìjiào","ne"],"txt":1},
  {"id":"2-16-2","lv":2,"h":"要","py":"yào","vi":"sẽ, muốn","en":"will","ex":"我要去学校。","exPy":"Wǒ yào qù xuéxiào.","exVi":"Tôi sẽ đi đến trường.","exEn":"I will go to school.","tok":["我","要","去","学校"],"tokPy":["wǒ","yào","qù","xuéxiào"],"txt":1},
  {"id":"2-16-3","lv":2,"h":"会","py":"huì","vi":"biết (làm gì)","en":"can","ex":"会骑自行车。","exPy":"Huì qí zìxíngchē.","exVi":"Biết đi xe đạp.","exEn":"Can ride a bike.","tok":["会","骑","自行车"],"tokPy":["huì","qí","zìxíngchē"],"txt":1},
  {"id":"2-17-0","lv":2,"h":"也","py":"yě","vi":"cũng","en":"too","ex":"我也是学生。","exPy":"Wǒ yě shì xuésheng.","exVi":"Tôi cũng là học sinh.","exEn":"I'm a student, too.","tok":["我","也","是","学生"],"tokPy":["wǒ","yě","shì","xuésheng"],"txt":1},
  {"id":"2-17-1","lv":2,"h":"怎么","py":"zěnme","vi":"thế nào, làm sao","en":"how","ex":"怎么办？","exPy":"Zěnme bàn?","exVi":"Làm sao bây giờ?","exEn":"How to do?","tok":["怎么","办"],"tokPy":["zěnme","bàn"],"txt":1},
  {"id":"2-17-2","lv":2,"h":"怎么样","py":"zěnmeyàng","vi":"thế nào","en":"how about","ex":"这个怎么样？","exPy":"Zhège zěnmeyàng?","exVi":"Cái này thế nào?","exEn":"How about this one?","tok":["这个","怎么样"],"tokPy":["zhège","zěnmeyàng"],"txt":1},
  {"id":"2-17-3","lv":2,"h":"真","py":"zhēn","vi":"thật là","en":"really","ex":"真好吃！","exPy":"Zhēn hǎochī!","exVi":"Ngon thật đấy!","exEn":"Really delicious!","tok":["真","好吃"],"tokPy":["zhēn","hǎochī"],"txt":1},
  {"id":"2-18-0","lv":2,"h":"做","py":"zuò","vi":"làm","en":"do","ex":"做作业","exPy":"zuò zuòyè","exVi":"làm bài tập","exEn":"do the homework","tok":["做","作业"],"tokPy":["zuò","zuòyè"],"txt":1},
  {"id":"3-01-0","lv":3,"h":"白","py":"bái","vi":"màu trắng","en":"white","ex":"白猫","exPy":"báimāo","exVi":"mèo trắng","exEn":"white cat","tok":["白","猫"],"tokPy":["bái","māo"]},
  {"id":"3-01-1","lv":3,"h":"饱","py":"bǎo","vi":"no","en":"full","ex":"我吃饱了。","exPy":"Wǒ chī bǎo le.","exVi":"Tôi ăn no rồi.","exEn":"I'm full.","tok":["我","吃","饱","了"],"tokPy":["wǒ","chī","bǎo","le"]},
  {"id":"3-01-2","lv":3,"h":"杯子","py":"bēizi","vi":"cái cốc","en":"cup","ex":"我的杯子","exPy":"wǒ de bēizi","exVi":"cốc của tôi","exEn":"my cup","tok":["我","的","杯子"],"tokPy":["wǒ","de","bēizi"]},
  {"id":"3-01-3","lv":3,"h":"本","py":"běn","vi":"quyển (vở)","en":"notebook","ex":"一个本子","exPy":"yí ge běnzi","exVi":"một quyển vở","exEn":"a notebook","tok":["一","个","本子"],"tokPy":["yí","ge","běnzi"]},
  {"id":"3-02-0","lv":3,"h":"唱歌","py":"chànggē","vi":"hát","en":"sing","ex":"她在唱歌。","exPy":"Tā zài chànggē.","exVi":"Cô ấy đang hát.","exEn":"She is singing.","tok":["她","在","唱歌"],"tokPy":["tā","zài","chànggē"]},
  {"id":"3-02-1","lv":3,"h":"车站","py":"chēzhàn","vi":"nhà ga, bến xe","en":"station","ex":"在车站","exPy":"zài chēzhàn","exVi":"ở bến xe","exEn":"at the station","tok":["在","车站"],"tokPy":["zài","chēzhàn"]},
  {"id":"3-02-2","lv":3,"h":"迟到","py":"chídào","vi":"đến muộn","en":"late","ex":"他迟到了。","exPy":"Tā chídào le.","exVi":"Cậu ấy đến muộn rồi.","exEn":"He was late.","tok":["他","迟到","了"],"tokPy":["tā","chídào","le"]},
  {"id":"3-02-3","lv":3,"h":"穿","py":"chuān","vi":"mặc","en":"wear","ex":"穿衣服","exPy":"chuān yīfu","exVi":"mặc quần áo","exEn":"wear clothes","tok":["穿","衣服"],"tokPy":["chuān","yīfu"]},
  {"id":"3-03-0","lv":3,"h":"打篮球","py":"dǎ lánqiú","vi":"chơi bóng rổ","en":"play basketball","ex":"他在打篮球。","exPy":"Tā zài dǎ lánqiú.","exVi":"Cậu ấy đang chơi bóng rổ.","exEn":"He is playing basketball.","tok":["他","在","打","篮球"],"tokPy":["tā","zài","dǎ","lánqiú"]},
  {"id":"3-03-1","lv":3,"h":"蛋糕","py":"dàngāo","vi":"bánh ngọt","en":"cake","ex":"买蛋糕","exPy":"mǎi dàngāo","exVi":"mua bánh ngọt","exEn":"buy a cake","tok":["买","蛋糕"],"tokPy":["mǎi","dàngāo"]},
  {"id":"3-03-2","lv":3,"h":"电影","py":"diànyǐng","vi":"phim","en":"movie","ex":"看电影","exPy":"kàn diànyǐng","exVi":"xem phim","exEn":"watch movie","tok":["看","电影"],"tokPy":["kàn","diànyǐng"]},
  {"id":"3-03-3","lv":3,"h":"动物园","py":"dòngwùyuán","vi":"sở thú","en":"zoo","ex":"去动物园","exPy":"qù dòngwùyuán","exVi":"đi sở thú","exEn":"go to the zoo","tok":["去","动物园"],"tokPy":["qù","dòngwùyuán"]},
  {"id":"3-04-0","lv":3,"h":"饿","py":"è","vi":"đói","en":"hungry","ex":"我饿了。","exPy":"Wǒ è le.","exVi":"Tôi đói rồi.","exEn":"I'm hungry.","tok":["我","饿","了"],"tokPy":["wǒ","è","le"]},
  {"id":"3-04-1","lv":3,"h":"飞机","py":"fēijī","vi":"máy bay","en":"plane","ex":"坐飞机","exPy":"zuò fēijī","exVi":"đi máy bay","exEn":"take a plane","tok":["坐","飞机"],"tokPy":["zuò","fēijī"]},
  {"id":"3-04-2","lv":3,"h":"感冒","py":"gǎnmào","vi":"bị cảm","en":"catch a cold","ex":"我感冒了。","exPy":"Wǒ gǎnmào le.","exVi":"Tôi bị cảm rồi.","exEn":"I catch a cold.","tok":["我","感冒","了"],"tokPy":["wǒ","gǎnmào","le"]},
  {"id":"3-04-3","lv":3,"h":"给","py":"gěi","vi":"cho, đưa","en":"give","ex":"给他一本书","exPy":"gěi tā yì běn shū","exVi":"đưa cậu ấy một quyển sách","exEn":"give him a book","tok":["给","他","一","本","书"],"tokPy":["gěi","tā","yì","běn","shū"]},
  {"id":"3-05-0","lv":3,"h":"公共汽车","py":"gōnggòng qìchē","vi":"xe buýt","en":"bus","ex":"坐公共汽车","exPy":"zuò gōnggòng qìchē","exVi":"đi xe buýt","exEn":"take a bus","tok":["坐","公共汽车"],"tokPy":["zuò","gōnggòngqìchē"]},
  {"id":"3-05-1","lv":3,"h":"刮风","py":"guāfēng","vi":"nổi gió","en":"windy","ex":"刮风了。","exPy":"Guā fēng le.","exVi":"Trời nổi gió rồi.","exEn":"It's windy.","tok":["刮风","了"],"tokPy":["guāfēng","le"]},
  {"id":"3-05-2","lv":3,"h":"果汁","py":"guǒzhī","vi":"nước ép hoa quả","en":"juice","ex":"喝果汁","exPy":"hē guǒzhī","exVi":"uống nước ép","exEn":"drink juice","tok":["喝","果汁"],"tokPy":["hē","guǒzhī"]},
  {"id":"3-05-3","lv":3,"h":"黑","py":"hēi","vi":"màu đen","en":"black","ex":"黑板","exPy":"hēibǎn","exVi":"bảng đen","exEn":"blackboard"},
  {"id":"3-06-0","lv":3,"h":"猴子","py":"hóuzi","vi":"con khỉ","en":"monkey","ex":"六只猴子","exPy":"liù zhī hóuzi","exVi":"sáu con khỉ","exEn":"six monkeys","tok":["六","只","猴子"],"tokPy":["liù","zhī","hóuzi"]},
  {"id":"3-06-1","lv":3,"h":"后","py":"hòu","vi":"phía sau","en":"behind","ex":"他在我后边。","exPy":"Tā zài wǒ hòubian.","exVi":"Cậu ấy ở phía sau tôi.","exEn":"He's behind me.","tok":["他","在","我","后边"],"tokPy":["tā","zài","wǒ","hòubian"]},
  {"id":"3-06-2","lv":3,"h":"坏","py":"huài","vi":"hỏng, xấu","en":"bad","ex":"苹果坏了。","exPy":"Píngguǒ huài le.","exVi":"Quả táo bị hỏng rồi.","exEn":"The apple is bad.","tok":["苹果","坏","了"],"tokPy":["píngguǒ","huài","le"]},
  {"id":"3-06-3","lv":3,"h":"欢迎","py":"huānyíng","vi":"chào mừng","en":"welcome","ex":"欢迎您！","exPy":"Huānyíng nín!","exVi":"Chào mừng ngài!","exEn":"Welcome!","tok":["欢迎","您"],"tokPy":["huānyíng","nín"]},
  {"id":"3-07-0","lv":3,"h":"回","py":"huí","vi":"trở về","en":"go back","ex":"回家","exPy":"huíjiā","exVi":"về nhà","exEn":"go back home","tok":["回","家"],"tokPy":["huí","jiā"]},
  {"id":"3-07-1","lv":3,"h":"花","py":"huā","vi":"bông hoa","en":"flower","ex":"花很美。","exPy":"Huā hěn měi.","exVi":"Bông hoa rất đẹp.","exEn":"Flower is beautiful.","tok":["花","很","美"],"tokPy":["huā","hěn","měi"]},
  {"id":"3-07-2","lv":3,"h":"鸡蛋","py":"jīdàn","vi":"trứng gà","en":"egg","ex":"很多鸡蛋","exPy":"hěn duō jīdàn","exVi":"rất nhiều trứng gà","exEn":"a lot of eggs","tok":["很多","鸡蛋"],"tokPy":["hěnduō","jīdàn"]},
  {"id":"3-07-3","lv":3,"h":"近","py":"jìn","vi":"gần","en":"close","ex":"很近","exPy":"hěn jìn","exVi":"rất gần","exEn":"very close","tok":["很","近"],"tokPy":["hěn","jìn"]},
  {"id":"3-08-0","lv":3,"h":"饺子","py":"jiǎozi","vi":"sủi cảo","en":"dumpling","ex":"吃饺子","exPy":"chī jiǎozi","exVi":"ăn sủi cảo","exEn":"eat dumplings","tok":["吃","饺子"],"tokPy":["chī","jiǎozi"]},
  {"id":"3-08-1","lv":3,"h":"开","py":"kāi","vi":"mở","en":"open","ex":"开门","exPy":"kāimén","exVi":"mở cửa","exEn":"open the door","tok":["开","门"],"tokPy":["kāi","mén"]},
  {"id":"3-08-2","lv":3,"h":"课","py":"kè","vi":"tiết học, bài học","en":"class","ex":"上课","exPy":"shàngkè","exVi":"vào học","exEn":"attend class","tok":["上","课"],"tokPy":["shàng","kè"]},
  {"id":"3-08-3","lv":3,"h":"哭","py":"kū","vi":"khóc","en":"cry","ex":"他哭了。","exPy":"Tā kū le.","exVi":"Cậu ấy khóc rồi.","exEn":"He cried.","tok":["他","哭","了"],"tokPy":["tā","kū","le"]},
  {"id":"3-09-0","lv":3,"h":"裤子","py":"kùzi","vi":"cái quần","en":"pants","ex":"穿裤子","exPy":"chuān kùzi","exVi":"mặc quần","exEn":"wear pants","tok":["穿","裤子"],"tokPy":["chuān","kùzi"]},
  {"id":"3-09-1","lv":3,"h":"快","py":"kuài","vi":"nhanh","en":"fast","ex":"兔子跑得快。","exPy":"Tùzi pǎo de kuài.","exVi":"Thỏ chạy rất nhanh.","exEn":"Rabbits run fast.","tok":["兔子","跑","得","快"],"tokPy":["tùzi","pǎo","de","kuài"]},
  {"id":"3-09-2","lv":3,"h":"可爱","py":"kě'ài","vi":"đáng yêu","en":"cute","ex":"小狗很可爱。","exPy":"Xiǎogǒu hěn kě'ài.","exVi":"Chú chó con rất đáng yêu.","exEn":"The dog is very cute.","tok":["小狗","很","可爱"],"tokPy":["xiǎogǒu","hěn","kěài"]},
  {"id":"3-09-3","lv":3,"h":"蓝","py":"lán","vi":"màu xanh lam","en":"blue","ex":"蓝天","exPy":"lántiān","exVi":"trời xanh","exEn":"blue sky"},
  {"id":"3-10-0","lv":3,"h":"老虎","py":"lǎohǔ","vi":"con hổ","en":"tiger","ex":"两只老虎","exPy":"liǎng zhī lǎohǔ","exVi":"hai con hổ","exEn":"two tigers","tok":["两","只","老虎"],"tokPy":["liǎng","zhī","lǎohǔ"]},
  {"id":"3-10-1","lv":3,"h":"累","py":"lèi","vi":"mệt","en":"tired","ex":"很累","exPy":"hěn lèi","exVi":"rất mệt","exEn":"very tired","tok":["很","累"],"tokPy":["hěn","lèi"]},
  {"id":"3-10-2","lv":3,"h":"礼物","py":"lǐwù","vi":"món quà","en":"present","ex":"生日礼物","exPy":"shēngrì lǐwù","exVi":"quà sinh nhật","exEn":"birthday present","tok":["生日","礼物"],"tokPy":["shēngrì","lǐwù"]},
  {"id":"3-10-3","lv":3,"h":"路","py":"lù","vi":"con đường","en":"road","ex":"马路","exPy":"mǎlù","exVi":"đường cái","exEn":"road"},
  {"id":"3-11-0","lv":3,"h":"卖","py":"mài","vi":"bán","en":"sell","ex":"卖衣服","exPy":"mài yīfu","exVi":"bán quần áo","exEn":"sell clothes","tok":["卖","衣服"],"tokPy":["mài","yīfu"]},
  {"id":"3-11-1","lv":3,"h":"慢","py":"màn","vi":"chậm","en":"slow","ex":"太慢了！","exPy":"Tài màn le!","exVi":"Chậm quá!","exEn":"It's too slow!","tok":["太","慢","了"],"tokPy":["tài","màn","le"]},
  {"id":"3-11-2","lv":3,"h":"忙","py":"máng","vi":"bận","en":"busy","ex":"他很忙。","exPy":"Tā hěn máng.","exVi":"Anh ấy rất bận.","exEn":"He is very busy.","tok":["他","很","忙"],"tokPy":["tā","hěn","máng"]},
  {"id":"3-11-3","lv":3,"h":"玫瑰花","py":"méiguihuā","vi":"hoa hồng","en":"rose","ex":"买玫瑰花","exPy":"mǎi méigui huā","exVi":"mua hoa hồng","exEn":"buy roses","tok":["买","玫瑰花"],"tokPy":["mǎi","méiguihuā"]},
  {"id":"3-12-0","lv":3,"h":"门","py":"mén","vi":"cửa","en":"door","ex":"开门","exPy":"kāimén","exVi":"mở cửa","exEn":"open the door","tok":["开","门"],"tokPy":["kāi","mén"]},
  {"id":"3-12-1","lv":3,"h":"面包","py":"miànbāo","vi":"bánh mì","en":"bread","ex":"吃面包","exPy":"chī miànbāo","exVi":"ăn bánh mì","exEn":"eat bread","tok":["吃","面包"],"tokPy":["chī","miànbāo"]},
  {"id":"3-12-2","lv":3,"h":"拿","py":"ná","vi":"cầm, lấy","en":"take","ex":"拿书","exPy":"ná shū","exVi":"cầm sách","exEn":"take the book","tok":["拿","书"],"tokPy":["ná","shū"]},
  {"id":"3-12-3","lv":3,"h":"奶奶","py":"nǎinai","vi":"bà nội","en":"grandmother","ex":"我的奶奶","exPy":"wǒ de nǎinai","exVi":"bà nội của tôi","exEn":"my grandmother","tok":["我","的","奶奶"],"tokPy":["wǒ","de","nǎinai"]},
  {"id":"3-13-0","lv":3,"h":"男","py":"nán","vi":"nam","en":"male","ex":"男孩","exPy":"nánhái","exVi":"bé trai","exEn":"boy"},
  {"id":"3-13-1","lv":3,"h":"您","py":"nín","vi":"ngài, ông, bà (kính trọng)","en":"you (polite)","ex":"您好！","exPy":"Nín hǎo!","exVi":"Xin chào ạ!","exEn":"Hello!","txt":1},
  {"id":"3-13-2","lv":3,"h":"女","py":"nǚ","vi":"nữ","en":"female","ex":"女孩","exPy":"nǚhái","exVi":"bé gái","exEn":"girl"},
  {"id":"3-13-3","lv":3,"h":"跑步","py":"pǎobù","vi":"chạy bộ","en":"run","ex":"他在跑步。","exPy":"Tā zài pǎobù.","exVi":"Cậu ấy đang chạy bộ.","exEn":"He is running.","tok":["他","在","跑步"],"tokPy":["tā","zài","pǎobù"]},
  {"id":"3-14-0","lv":3,"h":"裙子","py":"qúnzi","vi":"váy","en":"dress","ex":"穿裙子","exPy":"chuān qúnzi","exVi":"mặc váy","exEn":"wear dresses","tok":["穿","裙子"],"tokPy":["chuān","qúnzi"]},
  {"id":"3-14-1","lv":3,"h":"前","py":"qián","vi":"phía trước","en":"front","ex":"他在我前边。","exPy":"Tā zài wǒ qiánbian.","exVi":"Cậu ấy ở phía trước tôi.","exEn":"He's in front of me.","tok":["他","在","我","前边"],"tokPy":["tā","zài","wǒ","qiánbian"]},
  {"id":"3-14-2","lv":3,"h":"生病","py":"shēngbìng","vi":"bị ốm","en":"ill","ex":"他生病了。","exPy":"Tā shēngbìng le.","exVi":"Cậu ấy bị ốm rồi.","exEn":"He was ill.","tok":["他","生病","了"],"tokPy":["tā","shēngbìng","le"]},
  {"id":"3-14-3","lv":3,"h":"生日","py":"shēngrì","vi":"sinh nhật","en":"birthday","ex":"生日快乐！","exPy":"Shēngrì kuàilè!","exVi":"Chúc mừng sinh nhật!","exEn":"Happy birthday!","tok":["生日","快乐"],"tokPy":["shēngrì","kuàilè"]},
  {"id":"3-15-0","lv":3,"h":"水果","py":"shuǐguǒ","vi":"hoa quả","en":"fruit","ex":"吃水果","exPy":"chī shuǐguǒ","exVi":"ăn hoa quả","exEn":"eat fruit","tok":["吃","水果"],"tokPy":["chī","shuǐguǒ"]},
  {"id":"3-15-1","lv":3,"h":"少","py":"shǎo","vi":"ít","en":"few","ex":"西瓜太少了。","exPy":"Xīguā tài shǎo le.","exVi":"Dưa hấu ít quá.","exEn":"There are too few watermelons.","tok":["西瓜","太","少","了"],"tokPy":["xīguā","tài","shǎo","le"]},
  {"id":"3-15-2","lv":3,"h":"它","py":"tā","vi":"nó (con vật, đồ vật)","en":"it","ex":"它在睡觉。","exPy":"Tā zài shuìjiào.","exVi":"Nó đang ngủ.","exEn":"It's sleeping.","tok":["它","在","睡觉"],"tokPy":["tā","zài","shuìjiào"]},
  {"id":"3-15-3","lv":3,"h":"跳舞","py":"tiàowǔ","vi":"nhảy múa","en":"dance","ex":"他会跳舞。","exPy":"Tā huì tiàowǔ.","exVi":"Cậu ấy biết nhảy.","exEn":"He can dance.","tok":["他","会","跳舞"],"tokPy":["tā","huì","tiàowǔ"]},
  {"id":"3-16-0","lv":3,"h":"天气","py":"tiānqì","vi":"thời tiết","en":"weather","ex":"天气很好。","exPy":"Tiānqì hěn hǎo.","exVi":"Thời tiết rất đẹp.","exEn":"The weather is fine.","tok":["天气","很","好"],"tokPy":["tiānqì","hěn","hǎo"]},
  {"id":"3-16-1","lv":3,"h":"踢足球","py":"tī zúqiú","vi":"đá bóng","en":"play football","ex":"他在踢足球。","exPy":"Tā zài tī zúqiú.","exVi":"Cậu ấy đang đá bóng.","exEn":"He is playing football.","tok":["他","在","踢","足球"],"tokPy":["tā","zài","tī","zúqiú"]},
  {"id":"3-16-2","lv":3,"h":"太阳","py":"tàiyáng","vi":"mặt trời","en":"sun","ex":"这是太阳。","exPy":"Zhè shì tàiyáng.","exVi":"Đây là mặt trời.","exEn":"This is the sun.","tok":["这","是","太阳"],"tokPy":["zhè","shì","tàiyáng"]},
  {"id":"3-16-3","lv":3,"h":"外面","py":"wàimiàn","vi":"bên ngoài","en":"outside","ex":"外面在下雨。","exPy":"Wàimiàn zài xiàyǔ.","exVi":"Bên ngoài trời đang mưa.","exEn":"It's raining outside.","tok":["外面","在","下雨"],"tokPy":["wàimiàn","zài","xiàyǔ"]},
  {"id":"3-17-0","lv":3,"h":"玩","py":"wán","vi":"chơi","en":"play","ex":"玩游戏","exPy":"wán yóuxì","exVi":"chơi trò chơi","exEn":"play games","tok":["玩","游戏"],"tokPy":["wán","yóuxì"]},
  {"id":"3-17-1","lv":3,"h":"喂","py":"wèi","vi":"cho ăn","en":"feed","ex":"我在喂小羊。","exPy":"Wǒ zài wèi xiǎoyáng.","exVi":"Tôi đang cho cừu con ăn.","exEn":"I'm feeding the lamb.","tok":["我","在","喂","小羊"],"tokPy":["wǒ","zài","wèi","xiǎoyáng"]},
  {"id":"3-17-2","lv":3,"h":"洗澡","py":"xǐzǎo","vi":"tắm","en":"take a shower","ex":"他在洗澡。","exPy":"Tā zài xǐzǎo.","exVi":"Cậu ấy đang tắm.","exEn":"He is taking a shower.","tok":["他","在","洗澡"],"tokPy":["tā","zài","xǐzǎo"]},
  {"id":"3-17-3","lv":3,"h":"下雪","py":"xiàxuě","vi":"tuyết rơi","en":"snow","ex":"下雪了。","exPy":"Xiàxuě le.","exVi":"Tuyết rơi rồi.","exEn":"It's snowing.","tok":["下雪","了"],"tokPy":["xiàxuě","le"]},
  {"id":"3-18-0","lv":3,"h":"香蕉","py":"xiāngjiāo","vi":"quả chuối","en":"banana","ex":"买香蕉","exPy":"mǎi xiāngjiāo","exVi":"mua chuối","exEn":"buy bananas","tok":["买","香蕉"],"tokPy":["mǎi","xiāngjiāo"]},
  {"id":"3-18-1","lv":3,"h":"想","py":"xiǎng","vi":"muốn","en":"want","ex":"我想吃西瓜。","exPy":"Wǒ xiǎng chī xīguā.","exVi":"Tôi muốn ăn dưa hấu.","exEn":"I want some watermelon.","tok":["我","想","吃","西瓜"],"tokPy":["wǒ","xiǎng","chī","xīguā"]},
  {"id":"3-18-2","lv":3,"h":"鞋","py":"xié","vi":"giày","en":"shoes","ex":"新鞋","exPy":"xīn xié","exVi":"giày mới","exEn":"new shoes","tok":["新","鞋"],"tokPy":["xīn","xié"]},
  {"id":"3-18-3","lv":3,"h":"新","py":"xīn","vi":"mới","en":"new","ex":"新衣服","exPy":"xīn yīfu","exVi":"quần áo mới","exEn":"new clothes","tok":["新","衣服"],"tokPy":["xīn","yīfu"]},
  {"id":"3-19-0","lv":3,"h":"西瓜","py":"xīguā","vi":"dưa hấu","en":"watermelon","ex":"吃西瓜","exPy":"chī xīguā","exVi":"ăn dưa hấu","exEn":"eat watermelon","tok":["吃","西瓜"],"tokPy":["chī","xīguā"]},
  {"id":"3-19-1","lv":3,"h":"写","py":"xiě","vi":"viết","en":"write","ex":"写字","exPy":"xiězì","exVi":"viết chữ","exEn":"write","tok":["写","字"],"tokPy":["xiě","zì"]},
  {"id":"3-19-2","lv":3,"h":"药","py":"yào","vi":"thuốc","en":"medicine","ex":"吃药","exPy":"chīyào","exVi":"uống thuốc","exEn":"take medicine","tok":["吃","药"],"tokPy":["chī","yào"]},
  {"id":"3-19-3","lv":3,"h":"爷爷","py":"yéye","vi":"ông nội","en":"grandfather","ex":"他的爷爷","exPy":"tā de yéye","exVi":"ông nội của cậu ấy","exEn":"his grandfather","tok":["他","的","爷爷"],"tokPy":["tā","de","yéye"]},
  {"id":"3-20-0","lv":3,"h":"衣服","py":"yīfu","vi":"quần áo","en":"clothes","ex":"穿衣服","exPy":"chuān yīfu","exVi":"mặc quần áo","exEn":"wear clothes","tok":["穿","衣服"],"tokPy":["chuān","yīfu"]},
  {"id":"3-20-1","lv":3,"h":"一起","py":"yìqǐ","vi":"cùng nhau","en":"together","ex":"一起踢足球","exPy":"yìqǐ tī zúqiú","exVi":"cùng nhau đá bóng","exEn":"play football together","tok":["一起","踢","足球"],"tokPy":["yìqǐ","tī","zúqiú"]},
  {"id":"3-20-2","lv":3,"h":"游泳","py":"yóuyǒng","vi":"bơi","en":"swim","ex":"他会游泳。","exPy":"Tā huì yóuyǒng.","exVi":"Cậu ấy biết bơi.","exEn":"He can swim.","tok":["他","会","游泳"],"tokPy":["tā","huì","yóuyǒng"]},
  {"id":"3-20-3","lv":3,"h":"运动","py":"yùndòng","vi":"thể thao, vận động","en":"sports","ex":"他喜欢运动。","exPy":"Tā xǐhuan yùndòng.","exVi":"Cậu ấy thích thể thao.","exEn":"He likes sports.","tok":["他","喜欢","运动"],"tokPy":["tā","xǐhuan","yùndòng"]},
  {"id":"3-21-0","lv":3,"h":"远","py":"yuǎn","vi":"xa","en":"far","ex":"太远了。","exPy":"Tài yuǎn le.","exVi":"Xa quá.","exEn":"It's too far.","tok":["太","远","了"],"tokPy":["tài","yuǎn","le"]},
  {"id":"3-21-1","lv":3,"h":"右","py":"yòu","vi":"bên phải","en":"right","ex":"他在我右边。","exPy":"Tā zài wǒ yòubian.","exVi":"Cậu ấy ở bên phải tôi.","exEn":"He's on my right.","tok":["他","在","我","右边"],"tokPy":["tā","zài","wǒ","yòubian"]},
  {"id":"3-21-2","lv":3,"h":"知道","py":"zhīdao","vi":"biết","en":"know","ex":"不知道","exPy":"bù zhīdao","exVi":"không biết","exEn":"do not know","tok":["不","知道"],"tokPy":["bù","zhīdao"]},
  {"id":"3-21-3","lv":3,"h":"找","py":"zhǎo","vi":"tìm","en":"look for","ex":"找人","exPy":"zhǎo rén","exVi":"tìm người","exEn":"look for someone","tok":["找","人"],"tokPy":["zhǎo","rén"]},
  {"id":"3-22-0","lv":3,"h":"着急","py":"zháojí","vi":"sốt ruột, lo lắng","en":"anxious","ex":"他很着急。","exPy":"Tā hěn zháojí.","exVi":"Cậu ấy rất sốt ruột.","exEn":"He is very anxious.","tok":["他","很","着急"],"tokPy":["tā","hěn","zháojí"]},
  {"id":"3-22-1","lv":3,"h":"中午","py":"zhōngwǔ","vi":"buổi trưa","en":"noon","ex":"今天中午","exPy":"jīntiān zhōngwǔ","exVi":"trưa nay","exEn":"this noon","tok":["今天","中午"],"tokPy":["jīntiān","zhōngwǔ"]},
  {"id":"3-22-2","lv":3,"h":"自行车","py":"zìxíngchē","vi":"xe đạp","en":"bike","ex":"骑自行车","exPy":"qí zìxíngchē","exVi":"đi xe đạp","exEn":"ride a bike","tok":["骑","自行车"],"tokPy":["qí","zìxíngchē"]},
  {"id":"3-22-3","lv":3,"h":"左","py":"zuǒ","vi":"bên trái","en":"left","ex":"他在我左边。","exPy":"Tā zài wǒ zuǒbian.","exVi":"Cậu ấy ở bên trái tôi.","exEn":"He's on my left.","tok":["他","在","我","左边"],"tokPy":["tā","zài","wǒ","zuǒbian"]},
  {"id":"3-23-0","lv":3,"h":"走","py":"zǒu","vi":"đi bộ","en":"walk","ex":"走路","exPy":"zǒulù","exVi":"đi bộ","exEn":"walk","tok":["走","路"],"tokPy":["zǒu","lù"]},
  {"id":"3-23-1","lv":3,"h":"丢","py":"diū","vi":"mất, đánh rơi","en":"lost","ex":"我的书丢了。","exPy":"Wǒ de shū diū le.","exVi":"Tôi làm mất sách rồi.","exEn":"I lost my book.","tok":["我","的","书","丢","了"],"tokPy":["wǒ","de","shū","diū","le"]},
  {"id":"3-23-2","lv":3,"h":"到","py":"dào","vi":"đến nơi","en":"arrive","ex":"他到家了。","exPy":"Tā dàojiā le.","exVi":"Cậu ấy về đến nhà rồi.","exEn":"He is home.","tok":["他","到","家","了"],"tokPy":["tā","dào","jiā","le"]},
  {"id":"3-23-3","lv":3,"h":"舒服","py":"shūfu","vi":"dễ chịu, khỏe","en":"comfortable","ex":"我身体不舒服。","exPy":"Wǒ shēntǐ bù shūfu.","exVi":"Tôi thấy trong người không khỏe.","exEn":"I don't feel well.","tok":["我","身体","不","舒服"],"tokPy":["wǒ","shēntǐ","bù","shūfu"]},
  {"id":"3-24-0","lv":3,"h":"太","py":"tài","vi":"quá","en":"too","ex":"太短了！","exPy":"Tài duǎn le!","exVi":"Ngắn quá!","exEn":"It's too short!","tok":["太","短","了"],"tokPy":["tài","duǎn","le"],"txt":1},
  {"id":"3-24-1","lv":3,"h":"完","py":"wán","vi":"xong, hết","en":"finish","ex":"完成","exPy":"wánchéng","exVi":"hoàn thành","exEn":"complete"},
  {"id":"3-24-2","lv":3,"h":"下","py":"xià","vi":"xuống","en":"down","ex":"下车","exPy":"xiàchē","exVi":"xuống xe","exEn":"get off","tok":["下","车"],"tokPy":["xià","chē"]},
  {"id":"3-24-3","lv":3,"h":"现在","py":"xiànzài","vi":"bây giờ","en":"now","ex":"现在是八点。","exPy":"Xiànzài shì bā diǎn.","exVi":"Bây giờ là tám giờ.","exEn":"It's eight o'clock.","tok":["现在","是","八点"],"tokPy":["xiànzài","shì","bādiǎn"]},
  {"id":"3-25-0","lv":3,"h":"别","py":"bié","vi":"đừng","en":"don't","ex":"别跑！","exPy":"Bié pǎo!","exVi":"Đừng chạy!","exEn":"Don't run!","tok":["别","跑"],"tokPy":["bié","pǎo"]},
  {"id":"3-25-1","lv":3,"h":"最","py":"zuì","vi":"nhất","en":"the most","ex":"这个西瓜最大。","exPy":"Zhège xīguā zuì dà.","exVi":"Quả dưa hấu này to nhất.","exEn":"This watermelon is the biggest.","tok":["这个","西瓜","最","大"],"tokPy":["zhège","xīguā","zuì","dà"],"txt":1},
  {"id":"3-25-2","lv":3,"h":"所以","py":"suǒyǐ","vi":"cho nên, vì vậy","en":"so","ex":"因为我生病了，所以没有去学校。","exPy":"Yīnwèi wǒ shēngbìng le, suǒyǐ méiyǒu qù xuéxiào.","exVi":"Vì tôi bị ốm nên không đi học.","exEn":"I didn't go to school because I was ill.","tok":["因为","我","生病","了","所以","没有","去","学校"],"tokPy":["yīnwèi","wǒ","shēngbìng","le","suǒyǐ","méiyǒu","qù","xuéxiào"]},
  {"id":"3-25-3","lv":3,"h":"因为……所以……","py":"yīnwèi……suǒyǐ……","vi":"vì... nên...","en":"because... so...","ex":"因为我生病了，所以没有去学校。","exPy":"Yīnwèi wǒ shēngbìng le, suǒyǐ méiyǒu qù xuéxiào.","exVi":"Vì tôi bị ốm nên không đi học.","exEn":"I didn't go to school because I was ill.","tok":["因为","我","生病","了","所以","没有","去","学校"],"tokPy":["yīnwèi","wǒ","shēngbìng","le","suǒyǐ","méiyǒu","qù","xuéxiào"]},
  {"id":"3-26-0","lv":3,"h":"吧","py":"ba","vi":"nhé, nhỉ (trợ từ ngữ khí)","en":"modal particle","ex":"好吧。","exPy":"Hǎo ba.","exVi":"Thôi được.","exEn":"Alright.","txt":1},
  {"id":"3-26-1","lv":3,"h":"为什么","py":"wèi shénme","vi":"tại sao","en":"why","ex":"他为什么哭了？","exPy":"Tā wèi shénme kū le?","exVi":"Tại sao cậu ấy khóc?","exEn":"Why did he cry?","tok":["他","为什么","哭","了"],"tokPy":["tā","wèishénme","kū","le"],"txt":1},
  {"id":"4-01-0","lv":4,"h":"矮","py":"ǎi","vi":"thấp","en":"short","ex":"他很矮。","exPy":"Tā hěn ǎi.","exVi":"Cậu ấy rất thấp.","exEn":"He is short.","tok":["他","很","矮"],"tokPy":["tā","hěn","ǎi"]},
  {"id":"4-01-1","lv":4,"h":"搬","py":"bān","vi":"chuyển, dọn","en":"move","ex":"蚂蚁在搬家。","exPy":"Mǎyǐ zài bānjiā.","exVi":"Đàn kiến đang chuyển nhà.","exEn":"Ants are moving.","tok":["蚂蚁","在","搬家"],"tokPy":["mǎyǐ","zài","bānjiā"]},
  {"id":"4-01-2","lv":4,"h":"冰箱","py":"bīngxiāng","vi":"tủ lạnh","en":"refrigerator","ex":"买冰箱","exPy":"mǎi bīngxiāng","exVi":"mua tủ lạnh","exEn":"buy a refrigerator","tok":["买","冰箱"],"tokPy":["mǎi","bīngxiāng"]},
  {"id":"4-01-3","lv":4,"h":"饼干","py":"bǐnggān","vi":"bánh quy","en":"cookie","ex":"吃饼干","exPy":"chī bǐnggān","exVi":"ăn bánh quy","exEn":"eat cookies","tok":["吃","饼干"],"tokPy":["chī","bǐnggān"]},
  {"id":"4-02-0","lv":4,"h":"虫子","py":"chóngzi","vi":"con sâu, côn trùng","en":"insect","ex":"一只虫子","exPy":"yì zhī chóngzi","exVi":"một con sâu","exEn":"an insect","tok":["一","只","虫子"],"tokPy":["yì","zhī","chóngzi"]},
  {"id":"4-02-1","lv":4,"h":"床","py":"chuáng","vi":"cái giường","en":"bed","ex":"这是他的床。","exPy":"Zhè shì tā de chuáng.","exVi":"Đây là giường của cậu ấy.","exEn":"This is his bed.","tok":["这","是","他","的","床"],"tokPy":["zhè","shì","tā","de","chuáng"]},
  {"id":"4-02-2","lv":4,"h":"尝","py":"cháng","vi":"nếm","en":"taste","ex":"尝一尝","exPy":"cháng yi cháng","exVi":"nếm thử","exEn":"have a taste","tok":["尝","一","尝"],"tokPy":["cháng","yi","cháng"]},
  {"id":"4-02-3","lv":4,"h":"地铁","py":"dìtiě","vi":"tàu điện ngầm","en":"subway","ex":"坐地铁","exPy":"zuò dìtiě","exVi":"đi tàu điện ngầm","exEn":"take the subway","tok":["坐","地铁"],"tokPy":["zuò","dìtiě"]},
  {"id":"4-03-0","lv":4,"h":"地图","py":"dìtú","vi":"bản đồ","en":"map","ex":"看地图","exPy":"kàn dìtú","exVi":"xem bản đồ","exEn":"read a map","tok":["看","地图"],"tokPy":["kàn","dìtú"]},
  {"id":"4-03-1","lv":4,"h":"冬","py":"dōng","vi":"mùa đông","en":"winter","ex":"冬天很冷。","exPy":"Dōngtiān hěn lěng.","exVi":"Mùa đông rất lạnh.","exEn":"It's very cold in winter.","tok":["冬天","很","冷"],"tokPy":["dōngtiān","hěn","lěng"]},
  {"id":"4-03-2","lv":4,"h":"短","py":"duǎn","vi":"ngắn","en":"short","ex":"衣服很短。","exPy":"Yīfu hěn duǎn.","exVi":"Quần áo rất ngắn.","exEn":"The clothes are very short.","tok":["衣服","很","短"],"tokPy":["yīfu","hěn","duǎn"]},
  {"id":"4-03-3","lv":4,"h":"服务员","py":"fúwùyuán","vi":"người phục vụ","en":"waiter","ex":"他是服务员。","exPy":"Tā shì fúwùyuán.","exVi":"Anh ấy là người phục vụ.","exEn":"He is a waiter.","tok":["他","是","服务员"],"tokPy":["tā","shì","fúwùyuán"]},
  {"id":"4-04-0","lv":4,"h":"功夫","py":"gōngfu","vi":"võ công, kungfu","en":"kung fu","ex":"他会功夫。","exPy":"Tā huì gōngfu.","exVi":"Anh ấy biết võ kungfu.","exEn":"He knows kung fu.","tok":["他","会","功夫"],"tokPy":["tā","huì","gōngfu"]},
  {"id":"4-04-1","lv":4,"h":"公园","py":"gōngyuán","vi":"công viên","en":"park","ex":"在公园","exPy":"zài gōngyuán","exVi":"ở công viên","exEn":"in the park","tok":["在","公园"],"tokPy":["zài","gōngyuán"]},
  {"id":"4-04-2","lv":4,"h":"号码","py":"hàomǎ","vi":"số (điện thoại...)","en":"number","ex":"电话号码","exPy":"diànhuà hàomǎ","exVi":"số điện thoại","exEn":"phone number","tok":["电话","号码"],"tokPy":["diànhuà","hàomǎ"]},
  {"id":"4-04-3","lv":4,"h":"火车","py":"huǒchē","vi":"tàu hỏa","en":"train","ex":"坐火车","exPy":"zuò huǒchē","exVi":"đi tàu hỏa","exEn":"take a train","tok":["坐","火车"],"tokPy":["zuò","huǒchē"]},
  {"id":"4-05-0","lv":4,"h":"警察","py":"jǐngchá","vi":"cảnh sát","en":"police officer","ex":"他们是警察。","exPy":"Tāmen shì jǐngchá.","exVi":"Họ là cảnh sát.","exEn":"They are police officers.","tok":["他们","是","警察"],"tokPy":["tāmen","shì","jǐngchá"]},
  {"id":"4-05-1","lv":4,"h":"筷子","py":"kuàizi","vi":"đôi đũa","en":"chopstick","ex":"一双筷子","exPy":"yì shuāng kuàizi","exVi":"một đôi đũa","exEn":"a pair of chopsticks","tok":["一","双","筷子"],"tokPy":["yì","shuāng","kuàizi"]},
  {"id":"4-05-2","lv":4,"h":"脸","py":"liǎn","vi":"khuôn mặt","en":"face","ex":"她的脸","exPy":"tā de liǎn","exVi":"khuôn mặt cô ấy","exEn":"her face","tok":["她","的","脸"],"tokPy":["tā","de","liǎn"]},
  {"id":"4-05-3","lv":4,"h":"帽子","py":"màozi","vi":"cái mũ","en":"hat","ex":"买帽子","exPy":"mǎi màozi","exVi":"mua mũ","exEn":"buy a hat","tok":["买","帽子"],"tokPy":["mǎi","màozi"]},
  {"id":"4-06-0","lv":4,"h":"葡萄","py":"pútao","vi":"quả nho","en":"grape","ex":"吃葡萄","exPy":"chī pútao","exVi":"ăn nho","exEn":"eat grapes","tok":["吃","葡萄"],"tokPy":["chī","pútao"]},
  {"id":"4-06-1","lv":4,"h":"乒乓球","py":"pīngpāngqiú","vi":"bóng bàn","en":"table tennis","ex":"打乒乓球","exPy":"dǎ pīngpāngqiú","exVi":"chơi bóng bàn","exEn":"play table tennis","tok":["打","乒乓球"],"tokPy":["dǎ","pīngpāngqiú"]},
  {"id":"4-06-2","lv":4,"h":"桥","py":"qiáo","vi":"cây cầu","en":"bridge","ex":"桥很长。","exPy":"Qiáo hěn cháng.","exVi":"Cây cầu rất dài.","exEn":"The bridge is long.","tok":["桥","很","长"],"tokPy":["qiáo","hěn","cháng"]},
  {"id":"4-06-3","lv":4,"h":"晴","py":"qíng","vi":"nắng, quang đãng","en":"sunny","ex":"晴天","exPy":"qíngtiān","exVi":"ngày nắng","exEn":"sunny day"},
  {"id":"4-07-0","lv":4,"h":"秋","py":"qiū","vi":"mùa thu","en":"autumn","ex":"秋天","exPy":"qiūtiān","exVi":"mùa thu","exEn":"autumn"},
  {"id":"4-07-1","lv":4,"h":"上海","py":"Shànghǎi","vi":"Thượng Hải","en":"Shanghai","ex":"去上海","exPy":"qù Shànghǎi","exVi":"đi Thượng Hải","exEn":"go to Shanghai","tok":["去","上海"],"tokPy":["qù","Shànghǎi"]},
  {"id":"4-07-2","lv":4,"h":"刷牙","py":"shuāyá","vi":"đánh răng","en":"brush teeth","ex":"他在刷牙。","exPy":"Tā zài shuāyá.","exVi":"Cậu ấy đang đánh răng.","exEn":"He's brushing his teeth.","tok":["他","在","刷牙"],"tokPy":["tā","zài","shuāyá"]},
  {"id":"4-07-3","lv":4,"h":"树","py":"shù","vi":"cái cây","en":"tree","ex":"苹果树","exPy":"píngguǒshù","exVi":"cây táo","exEn":"apple tree","tok":["苹果","树"],"tokPy":["píngguǒ","shù"]},
  {"id":"4-08-0","lv":4,"h":"汤","py":"tāng","vi":"canh, súp","en":"soup","ex":"喝汤","exPy":"hē tāng","exVi":"uống canh","exEn":"drink soup","tok":["喝","汤"],"tokPy":["hē","tāng"]},
  {"id":"4-08-1","lv":4,"h":"兔子","py":"tùzi","vi":"con thỏ","en":"rabbit","ex":"三只兔子","exPy":"sān zhī tùzi","exVi":"ba con thỏ","exEn":"three rabbits","tok":["三","只","兔子"],"tokPy":["sān","zhī","tùzi"]},
  {"id":"4-08-2","lv":4,"h":"腿","py":"tuǐ","vi":"cái chân","en":"leg","ex":"他的腿","exPy":"tā de tuǐ","exVi":"chân của cậu ấy","exEn":"his leg","tok":["他","的","腿"],"tokPy":["tā","de","tuǐ"]},
  {"id":"4-08-3","lv":4,"h":"西红柿","py":"xīhóngshì","vi":"cà chua","en":"tomato","ex":"吃西红柿","exPy":"chī xīhóngshì","exVi":"ăn cà chua","exEn":"eat tomato","tok":["吃","西红柿"],"tokPy":["chī","xīhóngshì"]},
  {"id":"4-09-0","lv":4,"h":"羊肉","py":"yángròu","vi":"thịt cừu","en":"mutton","ex":"吃羊肉","exPy":"chī yángròu","exVi":"ăn thịt cừu","exEn":"eat mutton","tok":["吃","羊肉"],"tokPy":["chī","yángròu"]},
  {"id":"4-09-1","lv":4,"h":"云","py":"yún","vi":"mây","en":"cloud","ex":"云很美。","exPy":"Yún hěn měi.","exVi":"Mây rất đẹp.","exEn":"The cloud is beautiful.","tok":["云","很","美"],"tokPy":["yún","hěn","měi"]},
  {"id":"4-09-2","lv":4,"h":"圆","py":"yuán","vi":"tròn, hình tròn","en":"circle","ex":"圆形","exPy":"yuánxíng","exVi":"hình tròn","exEn":"circle"},
  {"id":"4-09-3","lv":4,"h":"周末","py":"zhōumò","vi":"cuối tuần","en":"weekend","ex":"今天是周末。","exPy":"Jīntiān shì zhōumò.","exVi":"Hôm nay là cuối tuần.","exEn":"Today is the weekend.","tok":["今天","是","周末"],"tokPy":["jīntiān","shì","zhōumò"]},
  {"id":"4-10-0","lv":4,"h":"种","py":"zhǒng","vi":"loại, kiểu","en":"kind of","ex":"三种水果","exPy":"sān zhǒng shuǐguǒ","exVi":"ba loại hoa quả","exEn":"three kinds of fruits","tok":["三","种","水果"],"tokPy":["sān","zhǒng","shuǐguǒ"],"txt":1},
  {"id":"4-10-1","lv":4,"h":"中间","py":"zhōngjiān","vi":"ở giữa","en":"middle","ex":"她站在中间。","exPy":"Tā zhàn zài zhōngjiān.","exVi":"Cô ấy đứng ở giữa.","exEn":"She stood in the middle.","tok":["她","站","在","中间"],"tokPy":["tā","zhàn","zài","zhōngjiān"]},
  {"id":"4-10-2","lv":4,"h":"放","py":"fàng","vi":"đặt, để","en":"put","ex":"书放在书包里。","exPy":"Shū fàng zài shūbāo lǐ.","exVi":"Sách để trong cặp.","exEn":"The books are in the bag.","tok":["书","放","在","书包","里"],"tokPy":["shū","fàng","zài","shūbāo","lǐ"]},
  {"id":"4-10-3","lv":4,"h":"贵","py":"guì","vi":"đắt","en":"expensive","ex":"飞机很贵。","exPy":"Fēijī hěn guì.","exVi":"Máy bay rất đắt.","exEn":"Airplanes are expensive.","tok":["飞机","很","贵"],"tokPy":["fēijī","hěn","guì"]},
  {"id":"4-11-0","lv":4,"h":"工作","py":"gōngzuò","vi":"làm việc","en":"work","ex":"他在工作。","exPy":"Tā zài gōngzuò.","exVi":"Anh ấy đang làm việc.","exEn":"He is working.","tok":["他","在","工作"],"tokPy":["tā","zài","gōngzuò"]},
  {"id":"4-11-1","lv":4,"h":"故事","py":"gùshi","vi":"câu chuyện","en":"story","ex":"听故事","exPy":"tīng gùshi","exVi":"nghe kể chuyện","exEn":"listen to the story","tok":["听","故事"],"tokPy":["tīng","gùshi"]},
  {"id":"4-11-2","lv":4,"h":"便宜","py":"piányi","vi":"rẻ","en":"cheap","ex":"香蕉很便宜。","exPy":"Xiāngjiāo hěn piányi.","exVi":"Chuối rất rẻ.","exEn":"Bananas are cheap.","tok":["香蕉","很","便宜"],"tokPy":["xiāngjiāo","hěn","piányi"]},
  {"id":"4-11-3","lv":4,"h":"甜","py":"tián","vi":"ngọt","en":"sweet","ex":"饼干很甜。","exPy":"Bǐnggān hěn tián.","exVi":"Bánh quy rất ngọt.","exEn":"Cookies are very sweet.","tok":["饼干","很","甜"],"tokPy":["bǐnggān","hěn","tián"]},
  {"id":"4-12-0","lv":4,"h":"停","py":"tíng","vi":"dừng, đỗ","en":"stop","ex":"停车","exPy":"tíngchē","exVi":"đỗ xe","exEn":"parking","tok":["停","车"],"tokPy":["tíng","chē"]},
  {"id":"4-12-1","lv":4,"h":"先","py":"xiān","vi":"trước tiên","en":"first","ex":"我先放鞋，然后放衣服，最后放水果。","exPy":"Wǒ xiān fàng xié, ránhòu fàng yīfu, zuìhòu fàng shuǐguǒ.","exVi":"Tôi để giày trước, sau đó để quần áo, cuối cùng để hoa quả.","exEn":"I put the shoes first, then the clothes, and the fruit last.","tok":["我","先","放","鞋","然后","放","衣服","最后","放","水果"],"tokPy":["wǒ","xiān","fàng","xié","ránhòu","fàng","yīfu","zuìhòu","fàng","shuǐguǒ"]},
  {"id":"4-12-2","lv":4,"h":"元","py":"yuán","vi":"đồng (nhân dân tệ)","en":"yuan","ex":"一本书十元。","exPy":"Yì běn shū shí yuán.","exVi":"Một quyển sách giá mười tệ.","exEn":"A book costs 10 yuan.","tok":["一","本","书","十","元"],"tokPy":["yì","běn","shū","shí","yuán"]},
  {"id":"4-12-3","lv":4,"h":"然后","py":"ránhòu","vi":"sau đó","en":"then","ex":"我先放鞋，然后放衣服，最后放水果。","exPy":"Wǒ xiān fàng xié, ránhòu fàng yīfu, zuìhòu fàng shuǐguǒ.","exVi":"Tôi để giày trước, sau đó để quần áo, cuối cùng để hoa quả.","exEn":"I put the shoes first, then the clothes, and the fruit last.","tok":["我","先","放","鞋","然后","放","衣服","最后","放","水果"],"tokPy":["wǒ","xiān","fàng","xié","ránhòu","fàng","yīfu","zuìhòu","fàng","shuǐguǒ"]},
  {"id":"4-13-0","lv":4,"h":"还是","py":"háishi","vi":"hay là","en":"or","ex":"买西瓜还是买葡萄？","exPy":"Mǎi xīguā háishi mǎi pútao?","exVi":"Mua dưa hấu hay mua nho?","exEn":"Buy watermelon or buy grapes?","tok":["买","西瓜","还是","买","葡萄"],"tokPy":["mǎi","xīguā","háishi","mǎi","pútao"]},
  {"id":"4-13-1","lv":4,"h":"用","py":"yòng","vi":"dùng","en":"use","ex":"用铅笔写字","exPy":"yòng qiānbǐ xiězì","exVi":"viết chữ bằng bút chì","exEn":"writing with pencil","tok":["用","铅笔","写字"],"tokPy":["yòng","qiānbǐ","xiězì"]}
];
